<% require "dotenv"; Dotenv.load(".env") if File.exist?(".env") %>

service: lamp-slim-react
image: <%= ENV.fetch("KAMAL_IMAGE") %>

servers:
  web:
    - <%= ENV.fetch("KAMAL_HOST") %>

proxy:
  app_port: 80
<% if ENV["KAMAL_DOMAIN"] && !ENV["KAMAL_DOMAIN"].empty? %>
  host: <%= ENV["KAMAL_DOMAIN"] %>
  ssl: true
<% end %>
  healthcheck:
    path: /up

registry:
<% if ENV["KAMAL_REGISTRY_SERVER"] && !ENV["KAMAL_REGISTRY_SERVER"].empty? %>
  server: <%= ENV["KAMAL_REGISTRY_SERVER"] %>
<% end %>
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .
  dockerfile: build/Dockerfile.deploy

env:
  clear:
    DB_HOST: db
    DB_DATABASE: <%= ENV.fetch("DB_DATABASE", "scuola") %>
    DB_USERNAME: <%= ENV.fetch("DB_USERNAME", "scuola") %>
  secret:
    - DB_PASSWORD

accessories:
  db:
    service: db
    image: mariadb:11.4
    host: <%= ENV.fetch("KAMAL_HOST") %>
    env:
      clear:
        MARIADB_DATABASE: <%= ENV.fetch("DB_DATABASE", "scuola") %>
        MARIADB_USER: <%= ENV.fetch("DB_USERNAME", "scuola") %>
      secret:
        - MARIADB_PASSWORD:DB_PASSWORD
        - MARIADB_ROOT_PASSWORD:DB_ROOT_PASSWORD
    directories:
      - data/mariadb:/var/lib/mysql
    files:
      - build/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
